### ISSUE TITLE
Debian 10 "Buster" Wayland Support Missing

### ISSUE THREAD

**Issue by DrTexx** [meghprkh/force-quit#11]
Out of the box Debian stable is now releasing with Wayland instead of Xorg.

Are we able to please please please get Wayland support if you've got time? <3

One of my favourite extensions and has saved my ass more than a few times!

**Comment by meghprkh** [comment]
Hi, I have been using Wayland on Fedora and haven't really caught up on the news, but is Debian removing XWayland too? If not then xkill shall work and I guess the upstream people will develop an alternative by the time they stop packaging XWayland by default.

(I dont really understand much, but XWayland is some kind of intermediate thing, and old X11 tools like xkill etc are supported via that at least on fedora afaik)

(For developing a pure Wayland alternative, we can prolly use evdev to get the pointer location and see how mutter gets the window clicked to switch apps)

Please test and report if it still works on Debian. (prolly try installing the package which provides xkill, if they removed installing it by default)

**Comment by MrCrayon** [comment]
Hi, @meghprkh thanks for this useful extension!
xkill only works on programs that uses X, so while using Wayland it only works in programs that are using XWayland.
If you hover a program that is using Wayland the X icon does not shows up at all.

I have no experience with gnome extensions but I can test it if you can find a solution, or even if you can point me to the documentation of something we can use I can give it a try.
As far as I can see we cannot use evdev either.

> evdev is an Xorg input driver

**Comment by meghprkh** [comment]
Hello, this should now be compatible with Wayland. Could you help me with testing? The steps are as mentioned

- Download the zip from here https://github.com/meghprkh/force-quit/archive/refs/heads/master.zip
- Extract the files inside at `~/.local/share/gnome-shell/extensions/fq@megh`
- Logout/Login and try force-quitting a window

**Comment by meghprkh** [comment]
The latest version has been approved on https://extensions.gnome.org and shall be available for update. Please re-open this issue if you face any issues with the new version.

**Comment by MrCrayon** [comment]
Just back from holiday, I can confirm it works perfectly well for both XWayland and Wayland in Gnome 41.2.
Thanks!
