### ISSUE TITLE
Support Gnome 3.38

### ISSUE THREAD

**Issue by davidbepo** [meghprkh/force-quit#12]
gnome 3.38 breaks the extension, please update it to support it

**Comment by meghprkh** [comment]
A new version has been uploaded to extensions.gnome.org and shall be available in a few days. Otherwise, you can overwrite `extension.js` in `~/.local/share/gnome-shell/extensions/fq@megh` with the [new content](https://github.com/meghprkh/force-quit/blob/master/extension.js)

**Comment by davidbepo** [comment]
okay, did overwrite and now it loads, but... woah
![Captura de pantalla de 2020-10-30 13-53-13](https://user-images.githubusercontent.com/18667173/97707543-b8ff2b80-1ab7-11eb-8401-c3d74d08cb21.png)

**Comment by meghprkh** [comment]
Ah, that looks clearly bugged. It works on the default theme. Could you
tell me your gnome shell theme's name/link?

**Comment by davidbepo** [comment]
actually here it does the same on default theme
![Captura de pantalla de 2020-10-30 14-43-59](https://user-images.githubusercontent.com/18667173/97712304-8b69b080-1abe-11eb-84b8-49a3ade11e41.png)
anyway the theme i use is xenlism

**Comment by meghprkh** [comment]
Indeed I had forgotten a line, this should be fixed by fc6aef1

**Comment by davidbepo** [comment]
yep, verified working properly now
