### ISSUE TITLE
Not compatible with Gnome 42 (Ubuntu 22.04 LTS)

### ISSUE THREAD

**Issue by leinardi** [meghprkh/force-quit#16]
The extension is not compatible with the latest stable version of Gnome:
![image](https://user-images.githubusercontent.com/273338/161421917-e87726da-dfdd-4c01-8f79-16f8c682ed4b.png)

https://extensions.gnome.org/extension/770/force-quit/

To reproduce the issue try to install the extension on Ubuntu 22.04 LTS.

**Comment by meghprkh** [comment]
Updated, please try again from the website

**Comment by leinardi** [comment]
Hi, I installed the update and the extension icon is shown correctly no on Gnome 42 but it does not work properly:
when I click the icon the cursor changes to a cross but I can't select anything nor I can cancel the action so the only solution is to restart. I tried twice and the result is the same.

**Comment by TowelSniffer** [comment]
Having the same issue described by @leinardi on Gnome 42 Arch

**Comment by ZimbiX** [comment]
When it gets stuck, nothing is logged from `journalctl -f /usr/bin/gnome-shell /usr/bin/gjs`.

To get out of it without closing your work, from a virtual terminal (e.g. Ctrl+Alt+F3), run `pkill '^gnome-shell$'`.

**Comment by meghprkh** [comment]
This should work now, please update the extension from the website

**Comment by ZimbiX** [comment]
Thanks for the update! It does indeed work now for me, and the highlighting is nice. But there are a few bugs:

- The cursor is not a crosshair when I hover over text elements in windows (and window elements react to hover)
- If I click on Gnome's top bar, the crosshair stops, but highlighting continues, Esc no longer cancels, and a window click still kills. I have to get out of it by clicking on the extension icon again then pressing Esc.
- Clicking on the extension icon, then hovering over a window, and repeating, increases the highlighting intensity

**Comment by meghprkh** [comment]
Updated yet again (thanks to https://github.com/EasyScreenCast/EasyScreenCast/pull/334 ), this time it should fix the bug. However the previous version introduced a behaviour which allowed to quit windows after pressing the super key and selecting from the overview, will try to see if I can add that back again

**Comment by meghprkh** [comment]
Closing this PR, created https://github.com/meghprkh/force-quit/issues/26 for the activity overview feature
