### ISSUE TITLE
Not working in gnome 46

### ISSUE THREAD

**Issue by foer** [meghprkh/force-quit#25]
Adding version 46 to metadata is not enough sadly...

**Comment by mtompkins** [comment]
Hope this super handy extension gets the love as well ... so underrated.

**Comment by meghprkh** [comment]
Thanks for the report. This extension closely contains / follows EasyScreenCast extension's window selection code. Thanks to @adangel , there is already a PR https://github.com/EasyScreenCast/EasyScreenCast/pull/356 . I will update the code once it is merged.

**Comment by meghprkh** [comment]
While I tried this in a VM, could you guys test the current zip from https://github.com/meghprkh/force-quit/archive/refs/heads/master.zip ?

**Comment by ZimbiX** [comment]
Thanks for the update! :heart: a6d9d13 is working well for me =)

```
➜ gnome-shell --version
GNOME Shell 46.0
```

**Comment by ZimbiX** [comment]
Actually, this part of the readme no longer applies, but it doesn't bother me at all:

> click on the top panel to abort the kill

**Comment by meghprkh** [comment]
Thanks, closing this as it is now published on GNOME extensions website. Updated the README as well :)
